# Generated by Django 4.0.4 on 2022-05-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='コード名')),
                ('key', models.IntegerField(verbose_name='基音')),
                ('octave', models.IntegerField(verbose_name='オクターブ')),
                ('chord', models.IntegerField(verbose_name='和音')),
                ('length', models.IntegerField(verbose_name='長さ')),
            ],
        ),
    ]
