# Generated by Django 4.0.4 on 2022-05-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chord', '0002_alter_tone_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tone',
            name='chord',
            field=models.CharField(max_length=255, verbose_name='和音'),
        ),
    ]
